services:
  mysql:
    image: mysql:8.0
    container_name: demoproduct-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "demoproduct"
      TZ: "UTC"
    ports:
      - "3306:3306"
    volumes:
      - demoproduct_mysql_data:/var/lib/mysql

volumes:
  demoproduct_mysql_data:

