spring.thymeleaf.cache=false
server.port=${SERVER_PORT:${PORT:8081}}

spring.datasource.url=jdbc:mysql://localhost:3306/demoproduct?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=11032004@Khang
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

